version: '3.8'
services:
  webapp:
    container_name: globalGold_web_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:80"
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    external: true
